### ISSUE TITLE
protocol origin

### ISSUE THREAD

**Issue by Andrei-Pozolotin** [albertcbraun/CMS50FW#1]
Albert, hi

where did you get the protocol from?

https://github.com/albertcbraun/CMS50FW/blob/master/Communication%20protocol%20of%20pulse%20oximeter%20V7.0.pdf

I would like to get an update

Thank you.

**Comment by albertcbraun** [comment]
i found that document back in 2014 or 2015 by googling. i cannot seem to find anything new about it now. i don't think CMS provides updates to this document. i'm very sorry i cannot help more with this.

**Comment by Andrei-Pozolotin** [comment]
thank you
